In [1]:
import numpy as np
import cvxpy as cp
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [8]:
aoe = pd.read_excel("aoe4_data.xlsx", index_col=0)
aoe = aoe.drop('Note', axis=1)
aoe.head()

,Unnamed: 1,Unnamed: 2,Resource Cost,Unnamed: 4,Unnamed: 5,Unnamed: 6,Time,Pop,Move,HP,HP per\nResource,Armor,Unnamed: 13,Attack,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Bonus
,,,,,,,,,,,,,,,,,,,,
Name,Civ,Age,NaN,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,Melee,Range,Dmg,Spd,Dps,Rng,dps/r,Type,NaN
Light Melee Infantry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spearman,All,I,60.0,20.0,0.0,80,15.0,1.0,1.25,70.0,0.875,0,0,6,1.75,3.428571,0.29,0.042857,Melee,+15 vs Cav
NaN,NaN,II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,1.125,0,0,8,1.75,4.571429,0.29,0.057143,NaN,+20 vs Cav
NaN,NaN,III,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.0,1.375,0,0,9,1.75,5.142857,0.29,0.064286,NaN,+23 vs Cav

In [ ]:
aoe_data = pd.read_csv